import { createRouter, createWebHistory } from 'vue-router'
import Home from '../views/Home.vue'
import Scenario from '../views/Scenario.vue'

const requireComponent = require.context('../components/aframe/scenarios/', true, /Scenario\.vue$/)
const autoGeneratedRoutes = requireComponent.keys().map(fileName => {
  // Obtener el nombre del componente del archivo
  const componentName = fileName.match(/^\.\/(.*)\.vue$/)[1]

  const kebabCaseName = componentName.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()

  const routeName = kebabCaseName.endsWith('-scenario') ? kebabCaseName.slice(0, -9) : kebabCaseName

  return {
    path: `/scenario/${routeName}`,
    name: componentName,
    component: requireComponent(fileName).default
  }
})

const manualRoutes = [
  {
    path: '/',
    name: 'Home',
    component: Home
  },
  {
    path: '/about',
    name: 'About',
    // route level code-splitting
    // this generates a separate chunk (about.[hash].js) for this route
    // which is lazy-loaded when the route is visited.
    component: () => import(/* webpackChunkName: "about" */ '../views/About.vue')
  },
  {
    path: '/scenario',
    name: 'Scenario',
    component: Scenario
  }
]

const routes = [...manualRoutes, ...autoGeneratedRoutes]

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes
})

console.log(router.getRoutes())

export default router
